name: Build Binary

on:
  release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust Executable
        run: cargo build --release

      - name: List Output Files
        run: ls -lah target/release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_rust_binary
          path: target/release/CI-CD-adventure
